---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

ci:
  # pre-commit.ci sandbox prevents network calls; disable gha-workflow-linter
  skip: [pytest, gha-workflow-linter]
  autofix_commit_msg: |
    Chore: pre-commit autofixes

    Signed-off-by: pre-commit-ci[bot] <pre-commit-ci@users.noreply.github.com>
  autoupdate_commit_msg: |
    Chore: pre-commit autoupdate

    Signed-off-by: pre-commit-ci[bot] <pre-commit-ci@users.noreply.github.com>

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        exclude: ^base/jenkins/templates/.*
      - id: check-added-large-files
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=main
          - --branch=rc
          - --branch=production

  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # frozen: v1.37.1
    hooks:
      - id: yamllint
        exclude: ^base/jenkins/templates/.*

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98  # frozen: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: https://github.com/fsfe/reuse-tool
    rev: 9fabf9eb815a57aac116b435e8346c200cdb8604  # frozen: v6.2.0
    hooks:
      - id: reuse
