apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-1password-sa-token
  namespace: {{ template "jenkins.namespace" . }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword-releng
  target:
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "Opensearch 1Password Service Account token/credential"
